with-expecter: True
dir: tests/mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  github.com/nemirlev/zenexport:
    config:
      recursive: True
  github.com/ClickHouse/clickhouse-go/v2/lib/driver:
    config:
      recursive: True