services:
    postgres:
        image: postgres:17
        container_name: zenexport_postgres
        ports:
        - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
    migrations:
        image: migrate/migrate
        container_name: zenexport_migrations
        volumes:
        - ../migrations/postgres:/migrations
        depends_on:
            postgres:
                condition: service_healthy
        command: -path=/migrations/ -database=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable up